/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface Trip {
    id: bigint;
    primaryCurrency: string;
    endDate?: Time;
    name: string;
    createdAt: Time;
    isActive: boolean;
    budgetLimit: number;
    startDate?: Time;
}
export type Time = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: HttpRequestResult;
}
export interface HttpRequestResult {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface ExchangeRate {
    code: string;
    rate: number;
    lastUpdated: Time;
}
export interface TripSummary {
    expensesByCategory: Array<[string, number]>;
    expenseCount: bigint;
    trip: Trip;
    totalSpent: number;
    percentUsed: number;
    remaining: number;
}
export interface Expense {
    id: bigint;
    localCurrency: string;
    convertedAmount: number;
    date: Time;
    note: string;
    createdAt: Time;
    tripId: bigint;
    conversionRate: number;
    category: string;
    amount: number;
}
export interface HttpHeader {
    value: string;
    name: string;
}
export interface backendInterface {
    addExpense(tripId: bigint, amount: number, localCurrency: string, category: string, note: string, date: Time): Promise<bigint>;
    createTrip(name: string, primaryCurrency: string, budgetLimit: number, startDate: Time | null, endDate: Time | null): Promise<bigint>;
    deleteApiKey(): Promise<boolean>;
    deleteExpense(id: bigint): Promise<boolean>;
    deleteTrip(id: bigint): Promise<boolean>;
    fetchAndStoreExchangeRates(): Promise<boolean>;
    getActiveTrip(): Promise<Trip | null>;
    getAllTrips(): Promise<Array<Trip>>;
    getApiKey(): Promise<string | null>;
    getAvailableCurrencies(): Promise<Array<string>>;
    getExchangeRates(): Promise<Array<ExchangeRate>>;
    getExpense(id: bigint): Promise<Expense | null>;
    getExpensesByCategory(tripId: bigint): Promise<Array<[string, number]>>;
    getExpensesEnabled(): Promise<boolean>;
    getExpensesForTrip(tripId: bigint): Promise<Array<Expense>>;
    getLastRateUpdate(): Promise<Time>;
    getTrip(id: bigint): Promise<Trip | null>;
    getTripSummary(tripId: bigint): Promise<TripSummary>;
    setActiveTrip(id: bigint): Promise<Trip>;
    setApiKey(key: string): Promise<boolean>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateExchangeRates(rates: Array<[string, number]>): Promise<boolean>;
    updateExpense(id: bigint, amount: number, localCurrency: string, category: string, note: string, date: Time): Promise<Expense>;
    updateTrip(id: bigint, name: string, primaryCurrency: string, budgetLimit: number, startDate: Time | null, endDate: Time | null): Promise<Trip>;
}
import type { Expense as _Expense, Time as _Time, Trip as _Trip, TripSummary as _TripSummary } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addExpense(arg0: bigint, arg1: number, arg2: string, arg3: string, arg4: string, arg5: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createTrip(arg0: string, arg1: string, arg2: number, arg3: Time | null, arg4: Time | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrip(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrip(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async deleteApiKey(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteApiKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteApiKey();
            return result;
        }
    }
    async deleteExpense(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteTrip(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrip(arg0);
            return result;
        }
    }
    async fetchAndStoreExchangeRates(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchAndStoreExchangeRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchAndStoreExchangeRates();
            return result;
        }
    }
    async getActiveTrip(): Promise<Trip | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveTrip();
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveTrip();
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTrips(): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrips();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrips();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiKey(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiKey();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiKey();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableCurrencies(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableCurrencies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableCurrencies();
            return result;
        }
    }
    async getExchangeRates(): Promise<Array<ExchangeRate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExchangeRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExchangeRates();
            return result;
        }
    }
    async getExpense(arg0: bigint): Promise<Expense | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpense(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpense(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpensesByCategory(arg0: bigint): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesByCategory(arg0);
            return result;
        }
    }
    async getExpensesEnabled(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesEnabled();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesEnabled();
            return result;
        }
    }
    async getExpensesForTrip(arg0: bigint): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesForTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesForTrip(arg0);
            return result;
        }
    }
    async getLastRateUpdate(): Promise<Time> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastRateUpdate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastRateUpdate();
            return result;
        }
    }
    async getTrip(arg0: bigint): Promise<Trip | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrip(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrip(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTripSummary(arg0: bigint): Promise<TripSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getTripSummary(arg0);
                return from_candid_TripSummary_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTripSummary(arg0);
            return from_candid_TripSummary_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async setActiveTrip(arg0: bigint): Promise<Trip> {
        if (this.processError) {
            try {
                const result = await this.actor.setActiveTrip(arg0);
                return from_candid_Trip_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setActiveTrip(arg0);
            return from_candid_Trip_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async setApiKey(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApiKey(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateExchangeRates(arg0: Array<[string, number]>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExchangeRates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExchangeRates(arg0);
            return result;
        }
    }
    async updateExpense(arg0: bigint, arg1: number, arg2: string, arg3: string, arg4: string, arg5: Time): Promise<Expense> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateTrip(arg0: bigint, arg1: string, arg2: string, arg3: number, arg4: Time | null, arg5: Time | null): Promise<Trip> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrip(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Trip_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrip(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Trip_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_TripSummary_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TripSummary): TripSummary {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Trip_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trip): Trip {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Trip]): Trip | null {
    return value.length === 0 ? null : from_candid_Trip_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Expense]): Expense | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expensesByCategory: Array<[string, number]>;
    expenseCount: bigint;
    trip: _Trip;
    totalSpent: number;
    percentUsed: number;
    remaining: number;
}): {
    expensesByCategory: Array<[string, number]>;
    expenseCount: bigint;
    trip: Trip;
    totalSpent: number;
    percentUsed: number;
    remaining: number;
} {
    return {
        expensesByCategory: value.expensesByCategory,
        expenseCount: value.expenseCount,
        trip: from_candid_Trip_n3(_uploadFile, _downloadFile, value.trip),
        totalSpent: value.totalSpent,
        percentUsed: value.percentUsed,
        remaining: value.remaining
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    primaryCurrency: string;
    endDate: [] | [_Time];
    name: string;
    createdAt: _Time;
    isActive: boolean;
    budgetLimit: number;
    startDate: [] | [_Time];
}): {
    id: bigint;
    primaryCurrency: string;
    endDate?: Time;
    name: string;
    createdAt: Time;
    isActive: boolean;
    budgetLimit: number;
    startDate?: Time;
} {
    return {
        id: value.id,
        primaryCurrency: value.primaryCurrency,
        endDate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.endDate)),
        name: value.name,
        createdAt: value.createdAt,
        isActive: value.isActive,
        budgetLimit: value.budgetLimit,
        startDate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.startDate))
    };
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trip>): Array<Trip> {
    return value.map((x)=>from_candid_Trip_n3(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
