/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Trip = IDL.Record({
  'id' : IDL.Nat,
  'primaryCurrency' : IDL.Text,
  'endDate' : IDL.Opt(Time),
  'name' : IDL.Text,
  'createdAt' : Time,
  'isActive' : IDL.Bool,
  'budgetLimit' : IDL.Float64,
  'startDate' : IDL.Opt(Time),
});
export const ExchangeRate = IDL.Record({
  'code' : IDL.Text,
  'rate' : IDL.Float64,
  'lastUpdated' : Time,
});
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'localCurrency' : IDL.Text,
  'convertedAmount' : IDL.Float64,
  'date' : Time,
  'note' : IDL.Text,
  'createdAt' : Time,
  'tripId' : IDL.Nat,
  'conversionRate' : IDL.Float64,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const TripSummary = IDL.Record({
  'expensesByCategory' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  'expenseCount' : IDL.Nat,
  'trip' : Trip,
  'totalSpent' : IDL.Float64,
  'percentUsed' : IDL.Float64,
  'remaining' : IDL.Float64,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  'addExpense' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, Time],
      [IDL.Nat],
      [],
    ),
  'createTrip' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Opt(Time), IDL.Opt(Time)],
      [IDL.Nat],
      [],
    ),
  'deleteApiKey' : IDL.Func([], [IDL.Bool], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTrip' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'fetchAndStoreExchangeRates' : IDL.Func([], [IDL.Bool], []),
  'getActiveTrip' : IDL.Func([], [IDL.Opt(Trip)], ['query']),
  'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getAvailableCurrencies' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getExchangeRates' : IDL.Func([], [IDL.Vec(ExchangeRate)], ['query']),
  'getExpense' : IDL.Func([IDL.Nat], [IDL.Opt(Expense)], ['query']),
  'getExpensesByCategory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getExpensesEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'getExpensesForTrip' : IDL.Func([IDL.Nat], [IDL.Vec(Expense)], ['query']),
  'getLastRateUpdate' : IDL.Func([], [Time], ['query']),
  'getTrip' : IDL.Func([IDL.Nat], [IDL.Opt(Trip)], ['query']),
  'getTripSummary' : IDL.Func([IDL.Nat], [TripSummary], ['query']),
  'setActiveTrip' : IDL.Func([IDL.Nat], [Trip], []),
  'setApiKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateExchangeRates' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      [IDL.Bool],
      [],
    ),
  'updateExpense' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, Time],
      [Expense],
      [],
    ),
  'updateTrip' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Opt(Time), IDL.Opt(Time)],
      [Trip],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Trip = IDL.Record({
    'id' : IDL.Nat,
    'primaryCurrency' : IDL.Text,
    'endDate' : IDL.Opt(Time),
    'name' : IDL.Text,
    'createdAt' : Time,
    'isActive' : IDL.Bool,
    'budgetLimit' : IDL.Float64,
    'startDate' : IDL.Opt(Time),
  });
  const ExchangeRate = IDL.Record({
    'code' : IDL.Text,
    'rate' : IDL.Float64,
    'lastUpdated' : Time,
  });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'localCurrency' : IDL.Text,
    'convertedAmount' : IDL.Float64,
    'date' : Time,
    'note' : IDL.Text,
    'createdAt' : Time,
    'tripId' : IDL.Nat,
    'conversionRate' : IDL.Float64,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const TripSummary = IDL.Record({
    'expensesByCategory' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    'expenseCount' : IDL.Nat,
    'trip' : Trip,
    'totalSpent' : IDL.Float64,
    'percentUsed' : IDL.Float64,
    'remaining' : IDL.Float64,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    'addExpense' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, Time],
        [IDL.Nat],
        [],
      ),
    'createTrip' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Opt(Time), IDL.Opt(Time)],
        [IDL.Nat],
        [],
      ),
    'deleteApiKey' : IDL.Func([], [IDL.Bool], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTrip' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'fetchAndStoreExchangeRates' : IDL.Func([], [IDL.Bool], []),
    'getActiveTrip' : IDL.Func([], [IDL.Opt(Trip)], ['query']),
    'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getAvailableCurrencies' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getExchangeRates' : IDL.Func([], [IDL.Vec(ExchangeRate)], ['query']),
    'getExpense' : IDL.Func([IDL.Nat], [IDL.Opt(Expense)], ['query']),
    'getExpensesByCategory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getExpensesEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'getExpensesForTrip' : IDL.Func([IDL.Nat], [IDL.Vec(Expense)], ['query']),
    'getLastRateUpdate' : IDL.Func([], [Time], ['query']),
    'getTrip' : IDL.Func([IDL.Nat], [IDL.Opt(Trip)], ['query']),
    'getTripSummary' : IDL.Func([IDL.Nat], [TripSummary], ['query']),
    'setActiveTrip' : IDL.Func([IDL.Nat], [Trip], []),
    'setApiKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateExchangeRates' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        [IDL.Bool],
        [],
      ),
    'updateExpense' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, Time],
        [Expense],
        [],
      ),
    'updateTrip' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Opt(Time),
          IDL.Opt(Time),
        ],
        [Trip],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };