/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ExchangeRate {
  'code' : string,
  'rate' : number,
  'lastUpdated' : Time,
}
export interface Expense {
  'id' : bigint,
  'localCurrency' : string,
  'convertedAmount' : number,
  'date' : Time,
  'note' : string,
  'createdAt' : Time,
  'tripId' : bigint,
  'conversionRate' : number,
  'category' : string,
  'amount' : number,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface Trip {
  'id' : bigint,
  'primaryCurrency' : string,
  'endDate' : [] | [Time],
  'name' : string,
  'createdAt' : Time,
  'isActive' : boolean,
  'budgetLimit' : number,
  'startDate' : [] | [Time],
}
export interface TripSummary {
  'expensesByCategory' : Array<[string, number]>,
  'expenseCount' : bigint,
  'trip' : Trip,
  'totalSpent' : number,
  'percentUsed' : number,
  'remaining' : number,
}
export interface _SERVICE {
  'addExpense' : ActorMethod<
    [bigint, number, string, string, string, Time],
    bigint
  >,
  'createTrip' : ActorMethod<
    [string, string, number, [] | [Time], [] | [Time]],
    bigint
  >,
  'deleteApiKey' : ActorMethod<[], boolean>,
  'deleteExpense' : ActorMethod<[bigint], boolean>,
  'deleteTrip' : ActorMethod<[bigint], boolean>,
  'fetchAndStoreExchangeRates' : ActorMethod<[], boolean>,
  'getActiveTrip' : ActorMethod<[], [] | [Trip]>,
  'getAllTrips' : ActorMethod<[], Array<Trip>>,
  'getApiKey' : ActorMethod<[], [] | [string]>,
  'getAvailableCurrencies' : ActorMethod<[], Array<string>>,
  'getExchangeRates' : ActorMethod<[], Array<ExchangeRate>>,
  'getExpense' : ActorMethod<[bigint], [] | [Expense]>,
  'getExpensesByCategory' : ActorMethod<[bigint], Array<[string, number]>>,
  'getExpensesEnabled' : ActorMethod<[], boolean>,
  'getExpensesForTrip' : ActorMethod<[bigint], Array<Expense>>,
  'getLastRateUpdate' : ActorMethod<[], Time>,
  'getTrip' : ActorMethod<[bigint], [] | [Trip]>,
  'getTripSummary' : ActorMethod<[bigint], TripSummary>,
  'setActiveTrip' : ActorMethod<[bigint], Trip>,
  'setApiKey' : ActorMethod<[string], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateExchangeRates' : ActorMethod<[Array<[string, number]>], boolean>,
  'updateExpense' : ActorMethod<
    [bigint, number, string, string, string, Time],
    Expense
  >,
  'updateTrip' : ActorMethod<
    [bigint, string, string, number, [] | [Time], [] | [Time]],
    Trip
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];